name: '[CI] Checkstyle, build and test automation'

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Codestyle check
        run: mvn checkstyle:check
        continue-on-error: true
      - name: Test with Maven
        run: mvn clean test
